### PR TITLE
Fix pkgutil style namespace pkgs

### PR DESCRIPTION
**Pull request by jay-tyler**
Hi Tim, 

This PR fixes pkgutil names, whether they are installed editably or not. We had 7x failing tests before and after this PR.

Would you mind testing against the implicit namespace package test cases you have?

Thanks!
Jason

### CODE REVIEW

**Comment by jay-tyler** [comment]
Ah, master actually was clean, got bit by a none editable install. Let me dig into these tests and try to understand what's going on.

There are a few weirdnesses, such as the `submodules` method allowing a module name with a dot in it. I'm guessing that's some kind of undocumented polymorphic behavior from before your fork.

**Comment by jay-tyler** [comment]
Ok, existing tests should be fixed now, but I need to add new testing. Import paths have always been picked up and resolved in practice (i.e. values that would be used in an `import ...` statement) , but there's no unittesting for doing so currently. We've only been testing for resolving submodules from relative file paths.

**Comment by jay-tyler** [comment]
So the prior doc string for `submodules` promised to return fully qualified submodule names, but it doesn't appear to be doing so. Not sure if this was some kind of legacy overlook in migrating from Py2 to Py3 code, or if the contract changed. See the test file for examples.

Surprisingly, things seem to work either way (with partial or qualified submodule names). Not sure yet why.

**Comment by timothycrosley** [comment]
This looks great! Thank you!

**Pull request merged**
